# Generated by Django 2.2.6 on 2020-10-08 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=600)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=25)),
                ('tipo_ie', models.CharField(choices=[('CONTRIBUINTE', 'CONTRIBUINTE'), ('NAO CONTRIBUINTE', 'NAO CONTRIBUINTE'), ('ISENTO', 'ISENTO')], default='CONTRIBUINTE', max_length=255)),
                ('inscricao_estadual', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('email_nfe', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
                ('possui_pedido_minimo', models.BooleanField()),
                ('pedido_minimo', models.FloatField()),
                ('possui_horario_pedido', models.BooleanField()),
                ('horario_pedido', models.TimeField()),
                ('comissao', models.FloatField()),
                ('banco', models.CharField(max_length=15)),
                ('agencia', models.CharField(max_length=30)),
                ('conta', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FormasPagamento',
            fields=[
                ('id_forma_pagamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_forma_pagamento', models.CharField(max_length=80)),
                ('prazo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TiposEmbalagem',
            fields=[
                ('id_tipo_embalagem', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposEmpresa',
            fields=[
                ('id_tipo_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TiposPessoa',
            fields=[
                ('id_tipo_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadesVenda',
            fields=[
                ('id_unidade_venda', models.AutoField(primary_key=True, serialize=False)),
                ('sigla', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=200)),
                ('permissao', models.CharField(choices=[('BASICA', 'BASICA'), ('PREPOSTO', 'PREPOSTO'), ('ADMINISTRADOR', 'ADMINISTRADOR')], default='BASICA', max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_produto', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=255)),
                ('custo_unitario', models.FloatField()),
                ('comissao', models.FloatField()),
                ('ipi', models.FloatField()),
                ('aliquota', models.FloatField()),
                ('reducao_icms', models.FloatField()),
                ('st', models.FloatField()),
                ('pis', models.FloatField()),
                ('mva_st', models.FloatField()),
                ('quantidade_embalagem', models.FloatField()),
                ('validade', models.IntegerField()),
                ('imagem', models.CharField(max_length=600)),
                ('ean', models.FloatField()),
                ('dun', models.FloatField()),
                ('preco_embalagem', models.FloatField()),
                ('possui_multiplo_venda', models.BooleanField()),
                ('multiplo', models.IntegerField()),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Categorias')),
                ('id_tipo_embalagem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.TiposEmbalagem')),
                ('id_unidade_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.UnidadesVenda')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pessoa', models.CharField(max_length=255)),
                ('aniversario', models.DateField()),
                ('lembrar_aniversario', models.BooleanField()),
                ('banco', models.CharField(max_length=15)),
                ('agencia', models.CharField(max_length=30)),
                ('conta', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('id_tipo_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.TiposPessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=50)),
                ('observacao', models.TextField()),
                ('data_pedido', models.DateField()),
                ('data_entrega', models.DateField()),
                ('horario_pedido', models.TimeField()),
                ('usuario_criacao', models.CharField(max_length=255)),
                ('usuario_modificacao', models.CharField(max_length=255)),
                ('data_modificacao', models.DateField()),
                ('id_empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_empresa_cliente', to='representacao.Empresas')),
                ('id_empresa_representada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_empresa_representada', to='representacao.Empresas')),
                ('id_forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.FormasPagamento')),
            ],
        ),
        migrations.AddField(
            model_name='empresas',
            name='id_tipo_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.TiposEmpresa'),
        ),
    ]
