# Generated by Django 2.2.6 on 2020-10-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.CharField(max_length=600)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=25)),
                ('tipo_ie', models.CharField(choices=[('CONTRIBUINTE', 'CONTRIBUINTE'), ('NAO CONTRIBUINTE', 'NAO CONTRIBUINTE'), ('ISENTO', 'ISENTO')], default='CONTRIBUINTE', max_length=255)),
                ('inscricao_estadual', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('email_nfe', models.EmailField(max_length=254)),
                ('endereco', models.CharField(max_length=80)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=80)),
                ('cep', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
                ('possui_pedido_minimo', models.BooleanField()),
                ('pedido_minimo', models.FloatField()),
                ('possui_horario_pedido', models.BooleanField()),
                ('horario_pedido', models.TimeField()),
                ('comissao', models.FloatField()),
                ('banco', models.CharField(max_length=15)),
                ('agencia', models.CharField(max_length=30)),
                ('conta', models.CharField(max_length=30)),
            ],
        ),
    ]
