# Generated by Django 2.2.6 on 2020-10-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0002_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='usuario_criacao',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='usuario_modificacao',
        ),
        migrations.AlterField(
            model_name='categorias',
            name='nome_categoria',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='agencia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='banco',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='comissao',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='conta',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email_nfe',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='horario_pedido',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='inscricao_estadual',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='logo',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome_fantasia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='pedido_minimo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='possui_horario_pedido',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='possui_pedido_minimo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='razao_social',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_ie',
            field=models.TextField(choices=[('CONTRIBUINTE', 'CONTRIBUINTE'), ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'), ('ISENTO', 'ISENTO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='uf',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='agencia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='bairro',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='banco',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cidade',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='comissao',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='complemento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='conta',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email_nfe',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='endereco',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='horario_pedido',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='inscricao_estadual',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nome_fantasia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='pedido_minimo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='possui_horario_pedido',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='possui_pedido_minimo',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='razao_social',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefone',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='tipo_ie',
            field=models.CharField(choices=[('CONTRIBUINTE', 'CONTRIBUINTE'), ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'), ('ISENTO', 'ISENTO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='uf',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='formaspagamento',
            name='nome_forma_pagamento',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='formaspagamento',
            name='prazo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_entrega',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_modificacao',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='numero_pedido',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='observacao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='agencia',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='aniversario',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='banco',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='cargo',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='conta',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='lembrar_aniversario',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='nome_pessoa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='telefone',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='aliquota',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo_produto',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comissao',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='custo_unitario',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='dun',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ean',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ipi',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='multiplo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='mva_st',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='pis',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='possui_multiplo_venda',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_embalagem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade_embalagem',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='reducao_icms',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='st',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='validade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tiposembalagem',
            name='tipo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tiposempresa',
            name='tipo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tipospessoa',
            name='tipo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unidadesvenda',
            name='sigla',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='permissao',
            field=models.CharField(choices=[('BASICA', 'BÁSICA'), ('PREPOSTO', 'PREPOSTO'), ('ADMINISTRADOR', 'ADMINISTRADOR')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
