# Generated by Django 2.2.6 on 2020-10-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0003_auto_20201010_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='comissao',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='horario_pedido',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='pedido_minimo',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='possui_horario_pedido',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='possui_pedido_minimo',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='agencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='bairro',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='banco',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='conta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email_nfe',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='endereco',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='logo',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefone',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_ie',
            field=models.TextField(blank=True, choices=[('CONTRIBUINTE', 'CONTRIBUINTE'), ('NAO CONTRIBUINTE', 'NÃO CONTRIBUINTE'), ('ISENTO', 'ISENTO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
