# Generated by Django 2.2.6 on 2020-10-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0004_auto_20201011_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='possui_horario_pedido',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='possui_pedido_minimo',
            field=models.BooleanField(),
        ),
    ]
