# Generated by Django 2.2.6 on 2020-10-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0006_auto_20201012_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='possui_multiplo_venda',
            field=models.BooleanField(),
        ),
    ]
