# Generated by Django 2.2.6 on 2020-10-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0007_auto_20201012_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='empresa',
            field=models.ManyToManyField(to='representacao.Empresas'),
        ),
    ]
