# Generated by Django 2.2.6 on 2020-10-13 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0008_pessoas_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='empresa',
            field=models.ManyToManyField(to='representacao.Empresas'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='agencia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='bairro',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='banco',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cep',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cidade',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='cnpj',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='comissao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='conta',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email_nfe',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='endereco',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='horario_pedido',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='inscricao_estadual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='pedido_minimo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefone',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Prepostos',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pessoa', models.CharField(blank=True, max_length=255, null=True)),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('lembrar_aniversario', models.BooleanField(null=True)),
                ('possui_vinculo_empresa', models.BooleanField(null=True)),
                ('informar_dados_bancarios', models.BooleanField(null=True)),
                ('banco', models.CharField(blank=True, max_length=15, null=True)),
                ('agencia', models.CharField(blank=True, max_length=30, null=True)),
                ('conta', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('comissao', models.FloatField(blank=True)),
                ('cliente', models.ManyToManyField(to='representacao.Clientes')),
                ('empresa', models.ManyToManyField(to='representacao.Empresas')),
                ('id_tipo_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.TiposPessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pessoa', models.CharField(blank=True, max_length=255, null=True)),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('lembrar_aniversario', models.BooleanField(null=True)),
                ('possui_vinculo_empresa', models.BooleanField(null=True)),
                ('informar_dados_bancarios', models.BooleanField(null=True)),
                ('banco', models.CharField(blank=True, max_length=15, null=True)),
                ('agencia', models.CharField(blank=True, max_length=30, null=True)),
                ('conta', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ManyToManyField(to='representacao.Clientes')),
                ('empresa', models.ManyToManyField(to='representacao.Empresas')),
                ('id_tipo_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.TiposPessoa')),
            ],
        ),
    ]
