# Generated by Django 2.2.6 on 2020-10-13 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0009_auto_20201013_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contatos',
            old_name='id_pessoa',
            new_name='id_contato',
        ),
        migrations.RenameField(
            model_name='contatos',
            old_name='nome_pessoa',
            new_name='nome_contato',
        ),
        migrations.RenameField(
            model_name='prepostos',
            old_name='id_pessoa',
            new_name='id_preposto',
        ),
        migrations.RenameField(
            model_name='prepostos',
            old_name='nome_pessoa',
            new_name='nome_preposto',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='aniversario',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='id_tipo_pessoa',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='informar_dados_bancarios',
        ),
        migrations.RemoveField(
            model_name='contatos',
            name='lembrar_aniversario',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='agencia',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='aniversario',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='conta',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='id_tipo_pessoa',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='informar_dados_bancarios',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='lembrar_aniversario',
        ),
    ]
