# Generated by Django 2.2.6 on 2020-10-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0010_auto_20201013_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='possui_vinculo_empresa',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='prepostos',
            name='possui_vinculo_empresa',
            field=models.BooleanField(),
        ),
    ]
