# Generated by Django 2.2.6 on 2020-10-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0011_auto_20201016_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='informar_dados_bancarios',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='lembrar_aniversario',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='possui_vinculo_empresa',
            field=models.BooleanField(),
        ),
    ]
