# Generated by Django 2.2.6 on 2020-10-16 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('representacao', '0012_auto_20201016_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='usario_django',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
