# Generated by Django 2.2.6 on 2020-10-16 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0013_usuarios_usario_django'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='usario_django',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
