# Generated by Django 2.2.6 on 2020-10-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0014_auto_20201016_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='usario_django',
            new_name='django_auth_user',
        ),
    ]
