# Generated by Django 2.2.6 on 2020-10-16 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0015_auto_20201016_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepostos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='nome_preposto',
        ),
        migrations.RemoveField(
            model_name='prepostos',
            name='telefone',
        ),
        migrations.AddField(
            model_name='prepostos',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='representacao.Usuarios'),
            preserve_default=False,
        ),
    ]
