# Generated by Django 2.2.6 on 2020-10-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0017_auto_20201016_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='prospectado_por_usuario',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
