# Generated by Django 2.2.6 on 2020-10-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0020_auto_20201019_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_modificacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
