# Generated by Django 2.2.6 on 2020-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0021_auto_20201019_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='aliquota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo_produto',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comissao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='custo_unitario',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='dun',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ipi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='multiplo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='mva_st',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='pis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_embalagem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade_embalagem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='reducao_icms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='st',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='validade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
