# Generated by Django 2.2.6 on 2020-10-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0024_auto_20201021_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
