# Generated by Django 2.2.6 on 2020-10-21 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0025_auto_20201021_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='imagem',
        ),
    ]
