# Generated by Django 2.2.6 on 2020-10-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0026_remove_produtos_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='imagem',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
