# Generated by Django 2.2.6 on 2020-10-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0027_produtos_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id_item_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.FloatField()),
                ('custo_total', models.FloatField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Pedidos')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Produtos')),
            ],
        ),
    ]
