# Generated by Django 2.2.6 on 2020-10-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0030_auto_20201023_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
