# Generated by Django 2.2.6 on 2020-10-23 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0032_auto_20201023_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(default=datetime.datetime(2020, 10, 23, 9, 49, 20, 552151), null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(9, 49, 20, 552151), null=True),
        ),
    ]
