# Generated by Django 2.2.6 on 2020-10-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0035_auto_20201027_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamentos',
            fields=[
                ('id_acompanhamento', models.AutoField(primary_key=True, serialize=False)),
                ('meta_geral', models.FloatField()),
                ('dias_uteis', models.IntegerField()),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.CreateModel(
            name='AcompanhamentoPreposto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_preposto', models.FloatField()),
                ('id_acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Acompanhamentos')),
                ('id_preposto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Prepostos')),
            ],
        ),
        migrations.CreateModel(
            name='AcompanhamentoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_empresa', models.FloatField()),
                ('id_acompanhamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Acompanhamentos')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Empresas')),
            ],
        ),
    ]
