# Generated by Django 2.2.6 on 2020-10-30 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0038_acompanhamentoprepostoempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='senha',
        ),
    ]
