# Generated by Django 2.2.6 on 2020-11-06 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0040_usuarios_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='cliente',
            field=models.ManyToManyField(to='representacao.Clientes'),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='possui_vinculo_cliente',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prepostos',
            name='possui_vinculo_cliente',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientes',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/uploads'),
        ),
    ]
