# Generated by Django 2.2.6 on 2020-11-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0041_auto_20201106_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='possui_vinculo_cliente',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
