# Generated by Django 2.2.6 on 2020-11-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0051_auto_20201113_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='data_modificacao',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='horario_pedido',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ordem_compra',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Pessoas',
        ),
    ]
