# Generated by Django 2.2.6 on 2020-11-13 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0052_auto_20201113_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TiposPessoa',
        ),
    ]
