# Generated by Django 2.2.6 on 2020-11-20 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0054_auto_20201117_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(default=datetime.date(2020, 11, 20), null=True),
        ),
    ]
