# Generated by Django 2.2.6 on 2020-11-30 19:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0056_auto_20201123_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='agencia',
            new_name='agencia_cliente',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='banco',
            new_name='banco_cliente',
        ),
        migrations.RenameField(
            model_name='clientes',
            old_name='conta',
            new_name='conta_cliente',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='agencia',
            new_name='agencia_empresa',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='banco',
            new_name='banco_emresa',
        ),
        migrations.RenameField(
            model_name='empresas',
            old_name='conta',
            new_name='conta_empresa',
        ),
        migrations.AddField(
            model_name='contatos',
            name='agencia_contato',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contatos',
            name='banco_contato',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contatos',
            name='conta_contato',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2020, 11, 30), null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='django_auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nome',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='permissao',
            field=models.CharField(choices=[('BASICA', 'BÁSICA'), ('PREPOSTO', 'PREPOSTO'), ('ADMINISTRADOR', 'ADMINISTRADOR')], max_length=30),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='telefone',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
