# Generated by Django 2.2.6 on 2020-12-03 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0057_auto_20201130_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresas',
            old_name='banco_emresa',
            new_name='banco_empresa',
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2020, 12, 3), null=True),
        ),
    ]
