# Generated by Django 2.2.6 on 2020-12-04 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0058_auto_20201203_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='representacao.Usuarios'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2020, 12, 4), null=True),
        ),
    ]
