# Generated by Django 2.2.6 on 2020-12-11 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0059_auto_20201204_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamentos',
            name='dias_trabalhados',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2020, 12, 11), null=True),
        ),
    ]
