# Generated by Django 2.2.6 on 2020-12-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0060_auto_20201211_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamentos',
            name='dias_trabalhados',
        ),
    ]
