# Generated by Django 2.2.6 on 2020-12-18 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0063_auto_20201211_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(blank=True, choices=[('AGUARDANDO FATURAMENTO', 'AGUARDANDO FATURAMENTO'), ('FATURADO', 'FATURADO'), ('CANCELADO', 'CANCELADO')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2020, 12, 18), null=True),
        ),
    ]
