# Generated by Django 2.2.6 on 2020-12-21 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0064_auto_20201218_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2020, 12, 21), null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(blank=True, choices=[('AGUARDANDO FATURAMENTO', 'AGUARDANDO FATURAMENTO'), ('FATURADO', 'FATURADO'), ('CANCELADO', 'CANCELADO')], default='AGUARDANDO FATURAMENTO', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='total_pedido',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
