# Generated by Django 2.2.6 on 2020-12-24 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0065_auto_20201221_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rotas',
            fields=[
                ('id_rota', models.AutoField(primary_key=True, serialize=False)),
                ('nome_rota', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2020, 12, 24), null=True),
        ),
        migrations.CreateModel(
            name='RotaPrepostos',
            fields=[
                ('id_rota_preposto', models.AutoField(primary_key=True, serialize=False)),
                ('id_preposto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Prepostos')),
                ('id_rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representacao.Rotas')),
            ],
        ),
        migrations.CreateModel(
            name='PrepostoClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s', models.BooleanField()),
                ('t', models.BooleanField()),
                ('q', models.BooleanField()),
                ('qi', models.BooleanField()),
                ('sx', models.BooleanField()),
                ('sa', models.BooleanField()),
                ('frequencia', models.CharField(blank=True, choices=[('SEMANAL', 'SEMANAL'), ('QUINZENAL', 'QUINZENAL'), ('MENSAL', 'MENSAL'), ('OUTRA', 'OUTRA')], max_length=30, null=True)),
                ('outra', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='representacao.Clientes')),
                ('id_rota_preposto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representacao.RotaPrepostos')),
            ],
        ),
    ]
