# Generated by Django 2.2.6 on 2021-01-08 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0067_auto_20210108_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prepostos',
            name='possui_vinculo_cliente',
        ),
    ]
