# Generated by Django 2.2.6 on 2021-01-28 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0069_auto_20210108_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='multiplo',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='possui_multiplo_venda',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='preco_embalagem',
        ),
        migrations.AddField(
            model_name='empresas',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(18, 22, 25, 661102)),
        ),
        migrations.AlterField(
            model_name='acompanhamentos',
            name='meta_geral',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itenspedido',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='representacao.Pedidos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_entrega',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2021, 1, 28)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id_contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='representacao.Contatos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='numero_pedido',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='ordem_compra',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prepostos',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='custo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade_embalagem',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
