# Generated by Django 2.2.6 on 2021-02-01 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0070_auto_20210128_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_entrega',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2021, 2, 1)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(10, 35, 23, 738017)),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='aliquota',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='dun',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ean',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='ipi',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='mva_st',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='pis',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='reducao_icms',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='st',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
