# Generated by Django 2.2.6 on 2021-02-10 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0071_auto_20210201_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_pedido',
            field=models.DateField(db_index=True, default=datetime.date(2021, 2, 10)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(16, 58, 20, 157844)),
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_tarefa', models.CharField(max_length=800, null=True)),
                ('data_incial', models.DateField(default=datetime.date(2021, 2, 10))),
                ('data_final', models.DateField(blank=True, default=datetime.date(2021, 2, 10), null=True)),
                ('frequencia', models.CharField(blank=True, choices=[('DIARIA', 'DIÁRIA'), ('SEMANAL', 'SEMANAL'), ('QUINZENAL', 'QUINZENAL'), ('MENSAL', 'MENSAL'), ('OUTRO', 'OUTRO')], max_length=30, null=True)),
                ('outra', models.CharField(blank=True, max_length=80, null=True)),
                ('usuario', models.ManyToManyField(blank=True, to='representacao.Usuarios')),
            ],
        ),
    ]
