# Generated by Django 2.2.6 on 2021-02-11 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0073_auto_20210211_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefas',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('A FAZER', 'A FAZER'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('CONCLUIDA', 'CONCLUÍDA'), ('REVISAO', 'REVISÃO'), ('CANCELADA', 'CANCELADA')], default='A FAZER', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(14, 21, 47, 818271)),
        ),
    ]
