# Generated by Django 2.2.6 on 2021-02-11 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0074_auto_20210211_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(17, 4, 45, 787711)),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='data_inicial',
            field=models.DateField(db_index=True, default=datetime.date(2021, 2, 11)),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='descricao_tarefa',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='frequencia',
            field=models.CharField(blank=True, choices=[('DIARIA', 'DIÁRIA'), ('SEMANAL', 'SEMANAL'), ('QUINZENAL', 'QUINZENAL'), ('MENSAL', 'MENSAL'), ('OUTRA', 'OUTRA')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tarefas',
            name='status',
            field=models.CharField(choices=[('A FAZER', 'A FAZER'), ('EM ANDAMENTO', 'EM ANDAMENTO'), ('CONCLUIDA', 'CONCLUÍDA'), ('REVISAO', 'REVISÃO'), ('CANCELADA', 'CANCELADA')], db_index=True, default='A FAZER', max_length=30),
        ),
    ]
