# Generated by Django 2.2.6 on 2021-02-12 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0078_auto_20210212_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(11, 27, 27, 65623)),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='numero_pedido',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
