# Generated by Django 2.2.6 on 2021-02-12 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0079_auto_20210212_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatos',
            name='nome_contato',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(11, 31, 10, 286732)),
        ),
    ]
