# Generated by Django 2.2.6 on 2021-02-12 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('representacao', '0080_auto_20210212_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='horario_pedido',
            field=models.TimeField(blank=True, default=datetime.time(11, 32, 20, 455936)),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='codigo_produto',
            field=models.CharField(db_index=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
    ]
